; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PhotoLabel"
#define MyAppVersion "260326"
#define MyAppPublisher "ykr.ltd"
#define MyAppURL "https://www.ykr.ltd"
#define MyAppExeName "PhotoLabel.exe"
#define PublishDir "Y:\Projects\job\int\aoyagi\source\PhotoLabel\bin\Release\net8.0-windows\win-x64\publish"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5ECE80C3-8EB2-4B1A-B9BA-6EAA0ED44ADB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=c:\ykr\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=Y:\Projects\job\int\aoyagi\source\PhotoLabel\setup\bin
OutputBaseFilename=PhotoLabelSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; self-contained publish縺ｮ蜈ｨ繝輔ぃ繧､繝ｫ・・NET Runtime繧貞酔譴ｱ縺吶ｋ縺溘ａ縲√う繝ｳ繧ｹ繝医・繝ｫ蜈医↓.NET荳崎ｦ・ｼ・
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "Config.ini"
; 譌｢蟄倥・Config.ini縺後≠繧句ｴ蜷医・荳頑嶌縺阪＠縺ｪ縺・
Source: "{#PublishDir}\Config.ini"; DestDir: "{app}"; Flags: ignoreversion onlyifdoesntexist
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

